INSERT INTO `Countries` (`id_country`, `id_region`, `Country`) VALUES
('AU', 6, 'Australia'),
('CN', 1, 'China'),
('JP', 1, 'Japan'),
('TH', 1, 'Thailand'),
('IN', 1, 'India'),
('MY', 1, 'Malaysia'),
('KR', 1, 'Korea'),
('HK', 1, 'Hong Kong'),
('TW', 1, 'Taiwan'),
('PH', 1, 'Philippines'),
('VN', 1, 'Vietnam'),
('FR', 5, 'France'),
('DE', 5, 'Germany'),
('SE', 5, 'Sweden'),
('IT', 5, 'Italy'),
('GR', 5, 'Greece'),
('ES', 5, 'Spain'),
('AT', 5, 'Austria'),
('GB', 5, 'United Kingdom'),
('NL', 5, 'Netherlands'),
('BE', 5, 'Belgium'),
('CH', 5, 'Switzerland'),
('AE', 2, 'United Arab Emirates'),
('IL', 2, 'Israel'),
('UA', 4, 'Ukraine'),
('RU', 4, 'Russian Federation'),
('KZ', 4, 'Kazakhstan'),
('PT', 5, 'Portugal'),
('SA', 2, 'Saudi Arabia'),
('DK', 5, 'Denmark'),
('IR', 2, 'Iran'),
('NO', 5, 'Norway'),
('US', 6, 'United States'),
('MX', 7, 'Mexico'),
('CA', 6, 'Canada'),
('SY', 2, 'Syrian Arab Republic'),
('CY', 5, 'Cyprus'),
('CZ', 5, 'Czech Republic'),
('IQ', 2, 'Iraq'),
('TR', 2, 'Turkey'),
('RO', 5, 'Romania'),
('LB', 2, 'Lebanon'),
('HU', 5, 'Hungary'),
('GE', 4, 'Georgia'),
('BR', 7, 'Brazil'),
('AZ', 4, 'Azerbaijan'),
('PS', 2, 'Palestinian Territory'),
('LT', 5, 'Lithuania'),
('OM', 2, 'Oman'),
('SK', 5, 'Slovakia'),
('RS', 5, 'Serbia'),
('FI', 5, 'Finland'),
('IS', 5, 'Iceland'),
('BG', 5, 'Bulgaria'),
('SI', 5, 'Slovenia'),
('MD', 4, 'Moldov'),
('MK', 5, 'Macedonia'),
('LI', 5, 'Liechtenstein'),
('PL', 5, 'Poland'),
('HR', 5, 'Croatia'),
('BA', 5, 'Bosnia and Herzegovina'),
('EE', 5, 'Estonia'),
('LV', 5, 'Latvia'),
('JO', 2, 'Jordan'),
('KG', 4, 'Kyrgyzstan'),
('IE', 5, 'Ireland'),
('LY', 2, 'Libya'),
('LU', 5, 'Luxembourg'),
('AM', 4, 'Armenia'),
('YE', 2, 'Yemen'),
('BY', 4, 'Belarus'),
('PA', 7, 'Panama'),
('DO', 7, 'Dominican Republic'),
('PR', 7, 'Puerto Rico'),
('MN', 1, 'Mongolia'),
('NZ', 6, 'New Zealand'),
('SG', 1, 'Singapore'),
('ID', 1, 'Indonesia'),
('NP', 1, 'Nepal'),
('PG', 6, 'Papua New Guinea'),
('PK', 1, 'Pakistan'),
('BS', 7, 'Bahamas'),
('AR', 7, 'Argentina'),
('BD', 1, 'Bangladesh'),
('MV', 1, 'Maldives'),
('AF', 1, 'Afghanistan'),
('FJ', 6, 'Fiji'),
('QA', 2, 'Qatar'),
('AL', 5, 'Albania'),
('UZ', 4, 'Uzbekistan'),
('KW', 2, 'Kuwait'),
('ME', 5, 'Montenegro'),
('PE', 7, 'Peru'),
('CO', 7, 'Colombia'),
('VE', 7, 'Venezuela'),
('CL', 7, 'Chile'),
('EC', 7, 'Ecuador'),
('ZA', 3, 'South Africa'),
('BO', 7, 'Bolivia'),
('EG', 2, 'Egypt'),
('ZW', 3, 'Zimbabwe'),
('LR', 3, 'Liberia'),
('KE', 3, 'Kenya'),
('GH', 3, 'Ghana'),
('NG', 3, 'Nigeria'),
('TZ', 3, 'Tanzani'),
('ZM', 3, 'Zambia'),
('MG', 3, 'Madagascar'),
('AO', 3, 'Angola'),
('NA', 3, 'Namibia'),
('CI', 3, 'Cote D''Ivoire'),
('SD', 3, 'Sudan'),
('CM', 3, 'Cameroon'),
('MW', 3, 'Malawi'),
('GA', 3, 'Gabon'),
('ML', 3, 'Mali'),
('CG', 3, 'Congo'),
('UG', 3, 'Uganda'),
('MA', 3, 'Morocco'),
('DZ', 3, 'Algeria'),
('SO', 3, 'Somalia'),
('NE', 3, 'Niger'),
('CR', 7, 'Costa Rica'),
('JM', 7, 'Jamaica'),
('GT', 7, 'Guatemala'),
('PY', 7, 'Paraguay'),
('SV', 7, 'El Salvador'),
('HN', 7, 'Honduras'),
('UY', 7, 'Uruguay'),
('KP', 1, 'North Korea'),
('FK', 7, 'Falkland Islands (Islas Malvinas)'),
('CU', 7, 'Cuba')