/*
-- Query: SELECT * FROM data_warehouse.countries
LIMIT 0, 1000

-- Date: 2021-12-05 11:11
*/
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'United Arab Emirates',1);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Afghanistan',2);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Albania',3);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Armenia',4);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Angola',5);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Argentina',6);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Austria',7);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (6,'Australia',8);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Azerbaijan',9);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Bosnia and Herzegovina',10);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Bangladesh',11);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Belgium',12);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Bulgaria',13);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Bolivia',14);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Brazil',15);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Bahamas',16);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Belarus',17);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (6,'Canada',18);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Congo',19);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Switzerland',20);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Cote D\'Ivoire',21);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Chile',22);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Cameroon',23);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'China',24);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Colombia',25);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Costa Rica',26);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Cuba',27);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Cyprus',28);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Czech Republic',29);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Germany',30);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Denmark',31);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Dominican Republic',32);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Algeria',33);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Ecuador',34);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Estonia',35);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Egypt',36);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Spain',37);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Finland',38);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (6,'Fiji',39);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Falkland Islands (Islas Malvinas)',40);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'France',41);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Gabon',42);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'United Kingdom',43);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Georgia',44);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Ghana',45);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Greece',46);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Guatemala',47);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Hong Kong',48);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Honduras',49);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Croatia',50);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Hungary',51);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Indonesia',52);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Ireland',53);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Israel',54);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'India',55);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Iraq',56);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Iran',57);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Iceland',58);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Italy',59);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Jamaica',60);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Jordan',61);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Japan',62);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Kenya',63);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Kyrgyzstan',64);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'North Korea',65);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Korea',66);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Kuwait',67);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Kazakhstan',68);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Lebanon',69);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Liechtenstein',70);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Liberia',71);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Lithuania',72);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Luxembourg',73);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Latvia',74);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Libya',75);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Morocco',76);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Moldov',77);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Montenegro',78);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Madagascar',79);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Macedonia',80);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Mali',81);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Mongolia',82);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Maldives',83);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Malawi',84);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Mexico',85);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Malaysia',86);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Namibia',87);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Niger',88);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Nigeria',89);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Netherlands',90);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Norway',91);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Nepal',92);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (6,'New Zealand',93);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Oman',94);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Panama',95);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Peru',96);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (6,'Papua New Guinea',97);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Philippines',98);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Pakistan',99);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Poland',100);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Puerto Rico',101);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Palestinian Territory',102);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Portugal',103);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Paraguay',104);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Qatar',105);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Romania',106);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Serbia',107);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Russian Federation',108);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Saudi Arabia',109);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Sudan',110);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Sweden',111);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Singapore',112);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Slovenia',113);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (5,'Slovakia',114);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Somalia',115);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'El Salvador',116);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Syrian Arab Republic',117);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Thailand',118);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Turkey',119);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Taiwan',120);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Tanzani',121);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Ukraine',122);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Uganda',123);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (6,'United States',124);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Uruguay',125);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (4,'Uzbekistan',126);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (7,'Venezuela',127);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (1,'Vietnam',128);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (2,'Yemen',129);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'South Africa',130);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Zambia',131);
INSERT INTO `` (`id_region`,`Country`,`id_country`) VALUES (3,'Zimbabwe',132);
